const createInMemoryModel = require("./inMemoryModel");

module.exports = createInMemoryModel("Flight", {
  airlineLogo: "",
  aircraftType: "A320",
  cabinClass: "Economy",
  status: "active",
  fromCity: "",
  fromAirport: "",
  fromCode: "",
  toCity: "",
  toAirport: "",
  toCode: "",
  departureDate: "",
  departureTime: "",
  arrivalDate: "",
  arrivalTime: "",
  duration: "",
  stops: "Non-stop",
  baseFare: 0,
  taxes: 0,
  platformFee: 0,
  ticketPrice: 0,
  totalSeats: 0,
  availableSeats: 0,
  bookedSeats: 0,
  blockedSeats: 0,
  seats: [],
  baggageAllowance: "",
  refundPolicy: "",
  cancellationPolicy: "",
});
