ALTER TABLE bookings
  ADD COLUMN IF NOT EXISTS pnr VARCHAR(32) NULL UNIQUE,
  ADD COLUMN IF NOT EXISTS seat_number VARCHAR(40) NULL,
  ADD COLUMN IF NOT EXISTS check_in_status ENUM('NOT_CHECKED_IN','CHECKED_IN') NOT NULL DEFAULT 'NOT_CHECKED_IN',
  ADD COLUMN IF NOT EXISTS boarding_pass_generated BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS qr_data TEXT NULL;

ALTER TABLE bookings
  MODIFY payment_status VARCHAR(40) NOT NULL DEFAULT 'pending',
  MODIFY booking_status VARCHAR(40) NOT NULL DEFAULT 'confirmed';

ALTER TABLE flight_bookings
  MODIFY seat_number VARCHAR(120) NULL,
  MODIFY booking_status VARCHAR(40) NOT NULL DEFAULT 'confirmed',
  MODIFY payment_status VARCHAR(40) NOT NULL DEFAULT 'paid';
