CREATE TABLE IF NOT EXISTS events (
  id VARCHAR(24) NOT NULL PRIMARY KEY,
  vendor_id VARCHAR(24) NOT NULL,
  event_name VARCHAR(255) NOT NULL,
  category VARCHAR(100) NOT NULL,
  event_type VARCHAR(100) NOT NULL,
  organizer_name VARCHAR(180) NOT NULL,
  event_date DATE NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  venue_name VARCHAR(255) NOT NULL,
  city VARCHAR(150) NOT NULL,
  address TEXT NOT NULL,
  ticket_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_tickets INT NOT NULL DEFAULT 0,
  available_tickets INT NOT NULL DEFAULT 0,
  poster_url LONGTEXT NULL,
  banner_url LONGTEXT NULL,
  description TEXT NULL,
  terms TEXT NULL,
  tags JSON NULL,
  state VARCHAR(150) NULL,
  country VARCHAR(100) NOT NULL DEFAULT 'India',
  map_url TEXT NULL,
  end_date DATE NULL,
  timezone VARCHAR(80) NOT NULL DEFAULT 'Asia/Kolkata',
  ticket_type VARCHAR(100) NOT NULL DEFAULT 'General Admission',
  booking_limit INT NOT NULL DEFAULT 10,
  early_bird_price DECIMAL(12,2) NULL,
  early_bird_until DATE NULL,
  gallery JSON NULL,
  thumbnail_url LONGTEXT NULL,
  video_url TEXT NULL,
  organizer_email VARCHAR(190) NULL,
  organizer_phone VARCHAR(40) NULL,
  organizer_website TEXT NULL,
  social_links JSON NULL,
  status ENUM('active','hidden','completed') NOT NULL DEFAULT 'active',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_events_vendor (vendor_id),
  INDEX idx_events_date_status (event_date, status),
  INDEX idx_events_city_category (city, category)
);

CREATE TABLE IF NOT EXISTS event_bookings (
  id VARCHAR(24) NOT NULL PRIMARY KEY,
  event_id VARCHAR(24) NOT NULL,
  user_id VARCHAR(24) NOT NULL,
  vendor_id VARCHAR(24) NOT NULL,
  customer_name VARCHAR(180) NOT NULL,
  customer_email VARCHAR(190) NOT NULL,
  quantity INT NOT NULL DEFAULT 1,
  total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  payment_status ENUM('pending','success','failed','refunded') NOT NULL DEFAULT 'pending',
  booking_status ENUM('pending','confirmed','cancelled','completed') NOT NULL DEFAULT 'confirmed',
  qr_code VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_event_bookings_event (event_id),
  INDEX idx_event_bookings_user (user_id),
  INDEX idx_event_bookings_vendor (vendor_id),
  UNIQUE KEY uq_event_booking_qr (qr_code)
);

CREATE TABLE IF NOT EXISTS event_notes (
  id VARCHAR(24) NOT NULL PRIMARY KEY,
  vendor_id VARCHAR(24) NOT NULL,
  event_id VARCHAR(24) NULL,
  note_title VARCHAR(255) NOT NULL,
  note_description TEXT NOT NULL,
  priority ENUM('low','medium','high') NOT NULL DEFAULT 'medium',
  status ENUM('open','in_progress','completed') NOT NULL DEFAULT 'open',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_event_notes_vendor (vendor_id),
  INDEX idx_event_notes_event (event_id)
);

CREATE TABLE IF NOT EXISTS event_booking_seats (
  id VARCHAR(24) NOT NULL PRIMARY KEY,
  booking_id VARCHAR(24) NOT NULL,
  event_id VARCHAR(24) NOT NULL,
  seat_no VARCHAR(20) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_event_seat (event_id, seat_no),
  INDEX idx_event_booking_seats_booking (booking_id)
);

CREATE TABLE IF NOT EXISTS event_coupons (
  id VARCHAR(24) NOT NULL PRIMARY KEY,
  vendor_id VARCHAR(24) NOT NULL,
  event_id VARCHAR(24) NULL,
  code VARCHAR(80) NOT NULL,
  discount_type ENUM('percent','fixed') NOT NULL DEFAULT 'percent',
  discount_value DECIMAL(12,2) NOT NULL DEFAULT 0,
  max_discount DECIMAL(12,2) NULL,
  valid_from DATE NOT NULL,
  valid_until DATE NOT NULL,
  usage_limit INT NULL,
  used_count INT NOT NULL DEFAULT 0,
  status ENUM('active','inactive') NOT NULL DEFAULT 'active',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_event_vendor_coupon (vendor_id, code),
  INDEX idx_event_coupons_event (event_id)
);
