ALTER TABLE flights
  ADD COLUMN IF NOT EXISTS flight_banner TEXT NULL,
  ADD COLUMN IF NOT EXISTS flight_thumbnail TEXT NULL,
  ADD COLUMN IF NOT EXISTS flight_gallery JSON NULL,
  ADD COLUMN IF NOT EXISTS seat_selection_mode ENUM('DURING_BOOKING','AFTER_BOOKING','CHECK_IN','AUTO_ASSIGN') NOT NULL DEFAULT 'CHECK_IN',
  ADD COLUMN IF NOT EXISTS check_in_open_hours_before INT NOT NULL DEFAULT 24;
