import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { QRCodeCanvas } from "qrcode.react";
import { hotelRequest, money, shortDate } from "../services/hotelApi";
import "./HotelModule.css";

export default function HotelConfirmation(){const{id}=useParams();const navigate=useNavigate();const[booking,setBooking]=useState(null),[error,setError]=useState("");useEffect(()=>{hotelRequest(`/user/hotel-bookings/${id}`).then(setBooking).catch(e=>setError(e.message));},[id]);if(error)return <div className="hotel-error">{error}</div>;if(!booking)return <div className="hotel-loading">Preparing your confirmation...</div>;
const downloadInvoice=()=>{const html=`<html><body style="font-family:Arial;padding:30px"><h1>TixHub Hotel Invoice</h1><p>Booking: ${booking.bookingCode}</p><h2>${booking.hotel_name}</h2><p>${shortDate(booking.check_in_date)} - ${shortDate(booking.check_out_date)}</p><p>Room: ${booking.room_name} x ${booking.room_count}</p><hr><p>Subtotal: ${money(booking.subtotal)}</p><p>Tax: ${money(booking.taxAmount)}</p><p>Discount: ${money(booking.discountAmount)}</p><h2>Total paid: ${money(booking.totalAmount)}</h2><p>Payment ID: ${booking.payment_id||"TixHub payment"}</p></body></html>`;const blob=new Blob([html],{type:"text/html"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`TixHub-${booking.bookingCode}-invoice.html`;a.click();URL.revokeObjectURL(url);};
return <div className="hotel-page"><div className="hotel-progress"><span className="active"/><span className="active"/><span className="active"/><span className="active"/></div><section className="hotel-panel hotel-success"><div className="hotel-success-mark">✓</div><h1>Hotel booked successfully!</h1><p>Your confirmation has been sent to {booking.guest_email}.</p><span className="hotel-status confirmed">{booking.bookingStatus}</span><h2>{booking.hotel_name}</h2><p>{booking.address}, {booking.city}</p><div className="hotel-qr"><QRCodeCanvas value={booking.qrToken} size={160}/></div><p><strong>Show this QR at hotel check-in</strong><br/>Booking ID: {booking.bookingCode}</p><div className="hotel-details-grid" style={{textAlign:"left"}}><div><div className="hotel-summary-row"><span>Check-in</span><strong>{shortDate(booking.check_in_date)} · {String(booking.check_in_time).slice(0,5)}</strong></div><div className="hotel-summary-row"><span>Check-out</span><strong>{shortDate(booking.check_out_date)} · {String(booking.check_out_time).slice(0,5)}</strong></div><div className="hotel-summary-row"><span>Room</span><strong>{booking.room_name} × {booking.room_count}</strong></div></div><div><div className="hotel-summary-row"><span>Guest</span><strong>{booking.guest_name}</strong></div><div className="hotel-summary-row total"><span>Paid</span><span>{money(booking.totalAmount)}</span></div></div></div><div style={{display:"flex",gap:10,justifyContent:"center",flexWrap:"wrap",marginTop:20}}><button className="hotel-btn" onClick={()=>navigate("/dashboard/my-hotel-bookings")}>My hotel bookings</button><button className="hotel-btn secondary" onClick={downloadInvoice}>Download invoice</button></div></section></div>}
