import { useEffect, useMemo, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { FaArrowLeft, FaChair, FaRupeeSign } from "react-icons/fa";
import "./SeatSelection.css";

const canonicalCategory=(value)=>{const key=String(value||"Regular").trim().toLowerCase().replace(/[\s-]+/g,"_");if(["vip","recliner","premium"].includes(key))return"VIP";if(["prime","prime_plus","classic_plus"].includes(key))return"Prime";if(["regular","classic"].includes(key))return"Regular";return key.replace(/_/g," ").replace(/\b\w/g,letter=>letter.toUpperCase())};
const displayCategory=(value)=>{const key=String(value||"Regular").trim().toLowerCase();if(key==="vip")return"VIP";if(key==="recliner")return"Recliner";return key.replace(/[_-]+/g," ").replace(/\b\w/g,letter=>letter.toUpperCase())};
const toSeatArray=(value)=>{if(Array.isArray(value))return value;if(!value)return[];if(typeof value==="string"){try{const parsed=JSON.parse(value);if(Array.isArray(parsed))return parsed}catch{return value.split(",").map(item=>item.trim()).filter(Boolean)}}if(typeof value==="object")return Object.values(value).flat();return[]};
const numericPart=(value)=>Number(String(value||"").replace(/\D/g,""))||0;
const displaySeatNumber=(seat,row)=>{const raw=String(seat.seatNumber||seat.seatNo||"").replace(new RegExp(`^${row}`,"i"),"");const number=raw.replace(/\D/g,"");return number?number.padStart(2,"0"):raw};
const categoryPriority=(name)=>({Recliner:0,VIP:0,Prime:1,Regular:2}[name]??3);
const isUnavailable=(seat)=>["booked","blocked","reserved","sold","unavailable"].includes(String(seat.status||"").toLowerCase())||seat.isBooked===true||seat.isBlocked===true||seat.blockedByVendor===true;
const isPremium=(seat)=>seat.isPremium===true||seat.premium===true||seat.bestseller===true||seat.isBestseller===true||String(seat.badge||"").toLowerCase()==="bestseller";

const groupLiveSeats=(seats)=>{const groups=new Map();seats.forEach(seat=>{const rawCategory=seat.seatType||seat.category||seat.categoryName||"Regular",name=displayCategory(rawCategory),row=seat.rowName||seat.row||String(seat.seatNo||seat.seatNumber||"").replace(/\d/g,"")||"A";if(!groups.has(name))groups.set(name,{category:name,canonical:canonicalCategory(rawCategory),rows:new Map(),prices:new Set()});const group=groups.get(name);if(!group.rows.has(row))group.rows.set(row,[]);group.rows.get(row).push({...seat,seatNo:seat.seatNo||seat.seatNumber,rowName:row});if(Number.isFinite(Number(seat.price)))group.prices.add(Number(seat.price))});return[...groups.values()].map(group=>({...group,prices:[...group.prices].sort((a,b)=>a-b),rows:[...group.rows.entries()].sort(([a],[b])=>a.localeCompare(b,undefined,{numeric:true})).map(([row,rowSeats])=>({row,seats:rowSeats.sort((a,b)=>numericPart(a.seatNumber||a.seatNo)-numericPart(b.seatNumber||b.seatNo))}))})).sort((a,b)=>categoryPriority(a.category)-categoryPriority(b.category)||a.category.localeCompare(b.category))};

export default function SeatSelection(){
 const navigate=useNavigate(),location=useLocation();
 const {movie,theatre,showtime,selectedSeats=2,category={}}=location.state||{};
 const [selected,setSelected]=useState([]),[liveSeats,setLiveSeats]=useState([]),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState("");
 const showId=movie?._id||movie?.id||"",activeCategory=canonicalCategory(category.name||category.category||"Regular");
 const legacyUnavailable=useMemo(()=>new Set([...toSeatArray(movie?.bookedSeats),...toSeatArray(movie?.blockedSeats)].map(String)),[movie?.bookedSeats,movie?.blockedSeats]);
 const seatByNumber=useMemo(()=>new Map(liveSeats.map(seat=>[String(seat.seatNo||seat.seatNumber),seat])),[liveSeats]);
 const sections=useMemo(()=>groupLiveSeats(liveSeats),[liveSeats]);
 const selectedRecords=useMemo(()=>selected.map(seatNo=>seatByNumber.get(String(seatNo))).filter(Boolean),[selected,seatByNumber]);
 const totalAmount=selectedRecords.reduce((total,seat)=>total+Number(seat.price||0),0);

 useEffect(()=>{if(!movie?._id&&!movie?.id){setLoading(false);return}const values={movieId:movie._id||movie.id,theatre:theatre?.name||theatre||"",screenId:movie.screenNumber||movie.screenName,showDate:showtime?.date?.value||showtime?.date?.label,showTime:showtime?.time,totalSeats:movie.totalSeats,regularSeats:movie.regularSeats,primeSeats:movie.primeSeats,vipSeats:movie.vipSeats,blockedSeats:movie.blockedSeats,blockedRegularSeats:movie.blockedRegularSeats,blockedPrimeSeats:movie.blockedPrimeSeats,blockedVipSeats:movie.blockedVipSeats,price:movie.ticketPrice,regularSeatPrice:movie.regularSeatPrice,premiumSeatPrice:movie.premiumSeatPrice||movie.primeSeatPrice,vipSeatPrice:movie.vipSeatPrice},params=new URLSearchParams();Object.entries(values).forEach(([key,value])=>{if(value!==undefined&&value!==null&&value!=="")params.set(key,value)});setLoading(true);setLoadError("");fetch(`http://localhost:5000/api/seats/${encodeURIComponent(showId)}?${params}`,{headers:{Authorization:`Bearer ${localStorage.getItem("token")||sessionStorage.getItem("token")}`}}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.message||"Unable to load seats");return data}).then(data=>setLiveSeats(Array.isArray(data.seats)?data.seats:[])).catch(error=>{setLiveSeats([]);setLoadError(error.message)}).finally(()=>setLoading(false))},[movie,showId,theatre,showtime]);

 if(!movie||!theatre||!showtime)return <div className="seat-empty"><h2>Booking details missing</h2><button onClick={()=>navigate("/dashboard/movies")}>Back to Movies</button></div>;

 const unavailable=(seat)=>isUnavailable(seat)||legacyUnavailable.has(String(seat.seatNo||seat.seatNumber));
 const toggleSeat=(seat,sectionCategory)=>{const seatNo=seat.seatNo||seat.seatNumber;if(canonicalCategory(sectionCategory)!==activeCategory||unavailable(seat))return;setSelected(current=>current.includes(seatNo)?current.filter(item=>item!==seatNo):current.length>=selectedSeats?current:[...current,seatNo])};
 const continueToPayment=()=>{const selectedCategory=selectedRecords[0]?.seatType||selectedRecords[0]?.category||category.name;const payload={movie,theatre,showtime,seats:selected,totalAmount,category:{...category,name:displayCategory(selectedCategory),price:selectedRecords[0]?.price}};sessionStorage.setItem("moviePayment",JSON.stringify(payload));navigate(`/dashboard/movies/${movie._id||movie.id}/payment`,{state:payload})};
 const dateLabel=[showtime.date?.label,showtime.date?.day,showtime.date?.month].filter(Boolean).join(" ");

 return <div className="seat-page"><header className="seat-header"><button className="back-btn" onClick={()=>navigate(-1)} aria-label="Back"><FaArrowLeft/></button><div className="seat-movie-info"><h1>{movie.title}</h1><p><strong>{theatre.name||theatre}</strong><span>{dateLabel||movie.showDate||"Selected date"}</span><span>{showtime.time}</span></p></div><span className="ticket-count">{selectedSeats} Tickets</span></header><main className="seat-content"><section className="seat-map-card"><div className="screen-box"><div className="screen-line"/><p>SCREEN THIS WAY</p></div>{loading?<SeatLoading/>:loadError?<div className="seat-map-message error"><strong>Unable to load seat map</strong><span>{loadError}</span></div>:sections.length?<div className="seat-scroll" aria-label="Movie seat map"><div className="seat-map-inner">{sections.map(section=><SeatSection key={section.category} section={section} selected={selected} activeCategory={activeCategory} unavailable={unavailable} toggleSeat={toggleSeat}/>)}</div></div>:<div className="seat-map-message"><strong>No seat inventory available</strong><span>Please choose another show or contact the theatre.</span></div>}<div className="legend"><span><i className="available"/>Available</span><span><i className="selected-box"/>Selected</span><span><i className="sold-box"/>Booked / Blocked</span><span><i className="premium-box"/>Bestseller</span></div></section></main><footer className="booking-footer"><div className="selected-summary"><FaChair/><span><small>Selected seats ({selected.length}/{selectedSeats})</small><strong>{selected.length?selected.join(", "):"Choose your seats"}</strong></span></div><div className="amount-summary"><small>Total amount</small><strong><FaRupeeSign/>{totalAmount}</strong></div><button disabled={selected.length!==selectedSeats} onClick={continueToPayment}>{selected.length===selectedSeats?`Continue · Rs ${totalAmount}`:`Select ${selectedSeats-selected.length} more`}</button></footer></div>;
}

function SeatSection({section,selected,activeCategory,unavailable,toggleSeat}){const priceLabel=section.prices.length===1?`₹${section.prices[0]}`:section.prices.length>1?`₹${section.prices[0]}–₹${section.prices.at(-1)}`:"Price unavailable";return <section className="seat-section"><header><span>{priceLabel} {section.category}</span></header>{section.rows.map(({row,seats})=><div className="seat-row" key={`${section.category}-${row}`}><span className="row-label">{row}</span><div className="seat-list">{seats.map((seat,index)=>{const seatNo=seat.seatNo||seat.seatNumber,sold=unavailable(seat),chosen=selected.includes(seatNo),disabled=section.canonical!==activeCategory,premium=isPremium(seat);return <button key={seatNo} title={sold?`${seatNo} booked or blocked`:`${seatNo} · ₹${Number(seat.price||0)}`} className={`seat ${sold?"sold":""} ${chosen?"selected":""} ${disabled?"disabled-seat":""} ${premium?"premium-seat":""} ${index>0&&index%5===0?"block-start":""}`} disabled={sold||disabled} onClick={()=>toggleSeat(seat,section.category)}>{displaySeatNumber(seat,row)}</button>})}</div></div>)}</section>}
function SeatLoading(){return <div className="seat-loading" aria-label="Loading seats">{Array.from({length:8},(_,row)=><div key={row}><i/>{Array.from({length:12},(_,seat)=><span key={seat}/>)}</div>)}</div>}
